language: node_js
node_js:
  - "6.4"

branches:
  only:
    - master

before_install:
  - rvm install 2.4.0

install:
  - bundle install
  - npm install -g firebase-tools

script:
  - jekyll build

after_success:
  - firebase deploy --token=${FIREBASE_TOKEN}
