name: "Derek Olson"
description: "Software Designer and Developer"
url: "https://www.derek-o.com"

permalink: /:categories/:title/
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude: [README.md, Gemfile, Gemfile.lock]
