name: "Derek Olson"
description: "Derek Olson - Creative Coder"
url: "http://www.derek-o.com"

permalink: /:categories/:title/
markdown: kramdown

exclude: [README.md, Gemfile, Gemfile.lock, firebase.json]
