name: "Derek Olson"
tagline: "Software Designer and Developer"
description: >
  Derek Olson is a software designer and developer with a background in art, music, and electronics.
  As a design lead at <a href="https://www.ideo.com">IDEO</a>,
  he collaborates with organizations around the world to create cutting-edge, 
  human-centered products and experiences.
url: "https://www.derek-o.com"
logo: "/img/logo-white-2x.png"

permalink: /:categories/:title/
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude: [README.md, Gemfile, Gemfile.lock]
